spring:
  application:
    name: sistema_consultas

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/sistema_consultas}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}

    show-sql: true

    properties:
      hibernate:
        format_sql: true

jwt:
    secret: $dXdrXdT9ewFBYdkX0yrr6UgxBkDfR5PJiivM4Kyjx4Cq5KFHOqeT3cfGQ8f3j5gd}
    expiration-minutes: ${JWT_EXPIRATION_MINUTES:30}